# -*- coding: utf-8 -*-
"""ImagemBrilhoAula17_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcQJ_L6W1t9wa4BQWZE8sEDprqn5eScw

Bibliotecas
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
from matplotlib import pyplot as plt
from google.colab import files
# %matplotlib inline

uploaded = files.upload()

img = cv2.imread('/content/sample_data/carro.webp')
imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
imgNC = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

fig = plt.figure(figsize=(30,20))
ax1 = fig.add_subplot(131)
plt.xticks([]), plt.yticks([])
plt.imshow(imgRGB)
plt.title("Imagem colorida")

ax2 = fig.add_subplot(132)
plt.xticks([]), plt.yticks([])
plt.imshow(imgNC, cmap= 'gray')
plt.title("Imagem niveis de cinza")

plt.show()

"""Histrograma"""

cv2.imwrite('img3_gray.jpg', imgNC)
gray = cv2.imread('img3_gray.jpg')

fig = plt.figure(figsize=(12, 12))

plt.subplots_adjust(left=0.125, bottom=0.1, right=1.5, top=1, wspace=0.33, hspace=0.2)
x1_plt = fig.add_subplot(1, 2, 1)
x2_plt = fig.add_subplot(1, 2, 2)

x1_plt.set_title("Imagem original")
x1_plt.imshow(imgRGB)
x2_plt.set_title("Imagem em niveis de cinza")
x2_plt.imshow(gray)
plt.show()

plt.hist(gray.ravel(), 255, [0,255]);
plt.show()

fig2 = plt.figure(figsize=(7, 7))
plt.subplots_adjust(left=0.125, bottom=0.1, right=1.5, top=1, wspace=0.33, hspace=0.2)

x1_plt = fig2.add_subplot(1, 2, 1)
x2_plt = fig2.add_subplot(1, 2, 2)


x1_plt.set_title("Imagem em niveis de cinza")
x1_plt.imshow(gray)
x2_plt.set_title("Histograma da Imagem ")
x2_plt.hist(gray.ravel(), 256, [0,256]);
plt.show()

dimensions = gray.shape
print('Dimensão da imagem é: ', dimensions)

azul, verde, vermelho = cv2.split(imgRGB)
plt.imshow(imgRGB)

fig6 = plt.figure(figsize=(8, 8))

plt.subplots_adjust(left=0.125, bottom=0.1, right=1.5, top=1, wspace=0.33, hspace=0.2)

x1_plt = fig6.add_subplot(1,3, 1)
x2_plt = fig6.add_subplot(1, 3, 2)
x3_plt = fig6.add_subplot(1, 3, 3)

x1_plt.imshow(azul, cmap='Blues_r')
x1_plt.set_title("Histograma no canal azul")
x2_plt.imshow(verde, cmap='Greens_r')
x2_plt.set_title("Histograma no canal verde")
x3_plt.imshow(vermelho, cmap='Reds_r')
x3_plt.set_title("Histograma no canal vermelho")
plt.show()

fig3 = plt.figure(figsize=(8, 8))

plt.subplots_adjust(left=0.125, bottom=0.1, right=1.5, top=1, wspace=0.33, hspace=0.2)

x1_plt = fig3.add_subplot(1, 3, 1)
x1_plt.hist(azul.ravel(), 256, [0,256])
x1_plt.set_title("Histograma no canal azul")

x2_plt = fig3.add_subplot(1, 3, 2)
x2_plt.hist(verde.ravel(), 256, [0,256])
x2_plt.set_title("Histograma no canal verde")

x3_plt = fig3.add_subplot(1, 3, 3)
x3_plt.hist(vermelho.ravel(), 256, [0,256])
x3_plt.set_title("Histograma no canal verde")

plt.show()

img_NC = cv2.imread("carro.webp", cv2.IMREAD_GRAYSCALE)
imgEqualizada = cv2.equalizeHist(img_NC)

fig4 = plt.figure(figsize=(10, 10))
plt.subplots_adjust(left=0.125, bottom=0.1, right=1.5, top=1, wspace=0.33, hspace=0.2)

x1_plt = fig4.add_subplot(1, 2, 1)
x1_plt.imshow(img_NC, cmap=plt.cm.gray)
x1_plt.set_title("Imagens em niveis de cinza")

x2_plt = fig4.add_subplot(1, 2, 2)
x2_plt.imshow(imgEqualizada, cmap=plt.cm.gray)
x2_plt.set_title("Imagens equalizada")

plt.show()

fig5 = plt.figure(figsize=(10, 10))
plt.subplots_adjust(left=0.125, bottom=0.1, right=1.5, top=1, wspace=0.33, hspace=0.2)

x1_plt = fig5.add_subplot(1, 2, 1)
x1_plt.hist(img_NC.ravel(), 256, [0, 256])
x1_plt.set_title("Imagens em niveis de cinza")

x2_plt = fig5.add_subplot(1, 2, 2)
x2_plt.hist(imgEqualizada.ravel(), 256, [0, 256])
x2_plt.set_title("Imagens equalizada")

plt.show()